package com.armybuilder.enums;

public enum Role {
    RIFLEMAN, AUTOMATIC_RIFLEMAN, GRENADIER, SAPPER, MACHINE_GUNNER, MORTAR_MAN, AMMO_BEARER, MEDIC, CORPSMAN, SCOUT, PIONEER  //ADD MORE AS NEEDED
}
